version: '3'

services:
  gibspons-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gibspons-api
    ports:
      - 80:8000
    volumes:
      - ./:/user/src/app
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - gibspons-network
    restart: always

  postgres:
    image: postgres
    container_name: gibspons-postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - gibspons-network
      
volumes:
  postgres-db:

networks:
  gibspons-network: